# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "backend/rvoc-backend/src/database/schema.rs"
with_docs = true
custom_type_derives = ["diesel::query_builder::QueryId", "diesel::sql_types::SqlType", "std::fmt::Debug"]

[migrations_directory]
dir = "backend/rvoc-backend/migrations"
